### PR TITLE
Async loop destroyer

### PR DESCRIPTION
**Pull request by Hopperpop**
Regarding jisotalo/node-red-contrib-ads-client#12
This is not a full fix, but more a proposal to start working from. 
What I see as a problem is that the ads-client starts in some parts async retry loops (ex. reconnecting), but doesn't have a good way to destroy these functions. Calling "clearTimeout" is not enough because if this is called while the callback functions is still executing, it could still start a new timeout and the loop continues. 

I added a mechanisme to destroy loops like this better for the reconnection and the _systemManagerStatePoller. 
There should be a function that fully destroys the ads-client with all the async loops, and I think that should be the disconnect function. The current problem is that the reconnection loop destroys itself because it calls the disconnect function (indirectly).  Maybe a split up is needed between a private and public disconnect function.

As you understand the code better, I want to hear what your opinion is about this approach, and if this even make any sense.

### CODE REVIEW

**Comment by jisotalo** [comment]
Thanks @Hopperpop, I'll try to check it out some day with a thought

This surely needs some fixing. Luckily it hasn't really been a problem in other than Node-RED systems.

**Comment by Hopperpop** [comment]
I'm using it also without any issues, as the system is stable and don't need any restart/redeploy. It's only an issue on systems that destroys the client. 
In the past I was working on a test-rig that had a lot of these type of issues (memory leaks/ unclosed references/...), and it was a pain to find solutions or workarounds. That's why I push a little bit (and help) to get it solved.

**Comment by jisotalo** [comment]
I developed it a little bit further. However, haven't yet tested and there is still that problem with disconnect() call.

Probably we need to do, like you said, an internal `_disconnect()` function.

Do you have a good test setup for this when it's ready? We need to be sure everything works as they should when releasing this.

**Comment by jisotalo** [comment]
@Hopperpop I developed this further. What do you think? I created new private `_connect()`, `_reconnect()` and `_disconnect()` functions to handle reconnecting better.

Needs testing before releasing.

**Comment by jisotalo** [comment]
Added minor bug fixes that I found when further developing `ads-server` (adding this new system there too).

**Comment by jisotalo** [comment]
Merged! Everything worked fine in my tests at least (local system and also with raspberry pi + node-red).

**Comment by Hopperpop** [comment]
Sorry for the slow reply. All the previous tests seems to work fine for me with the new code. I currently can't find any issue.
Thanks!

**Comment by jisotalo** [comment]
Thanks! Let me know if you find any problems :)

**Pull request merged**
