### PR TITLE
(v2) automatically delete stale subscriptions

### PR DESCRIPTION
**Pull request by crishoj**
Proposal for #150:

- Extracts a `deleteNotificationHandle(notificationHandle: number, targetAmsAddress: AmsAddress)` method.
- Introduces a `deleteUnknownSubscriptions` option (default `true`).
- Lets `onAdsCommandReceived()` automatically delete unknown subscriptions when `deleteUnknownSubscriptions` is set. Warning will be emitted regardless.

I'm currently away from my TwinCAT machine, so wasn't able to test this against a running system. Suggest holding back on merging until it's fully tested. Perhaps worthwhile to write a test for the new setting?

### CODE REVIEW

**Comment by jisotalo** [comment]
Looks great, thanks! Just that one comment about the `warn()` calls.

I can run the tests after marging to make sure everything works.

We could also try to add test for that later. I think it would probably be possible with a `disconnect(true)` call and then connecting again with the same ADS port. That should keep the subscriptions running.

**Comment by crishoj** [comment]
I've attempted to write a test for the stale subscription cleanup.

**Comment by jisotalo** [comment]
I'll check this in few days!

Too busy at work

**Comment by crishoj** [comment]
All good, also busy here!

**Comment by jisotalo** [comment]
I tried to push changes here but failed something. Probably need to use Github cli to do that..?

However, I updated some code and created working tests for the `deleteUnknownSubscriptions` setting. It needed a separate client with static ADS port. Without that, the port would not be the same and client wouldn't get any stale notifications.

If you can merge https://github.com/jisotalo/ads-client/tree/crishoj-v2-delete-unknown-subscriptions to your branch, see the changes and push them to update this PR? 

And also teach me how to add changes to someone elses PR correctly..

**Comment by crishoj** [comment]
> And also teach me how to add changes to someone elses PR correctly... :)

Good question, haven't tried this myself.

I do have this box checked in the PR:

image

Instructions read as follows:

image

I assume the procedure would be:

1. Add my fork as a "Git remote": `git remote add crishoj git@github.com:crishoj/ads-client.git`
2. Push to that fork: `git push crishoj`

**Comment by crishoj** [comment]
> If you can merge https://github.com/jisotalo/ads-client/tree/crishoj-v2-delete-unknown-subscriptions to your branch, see the changes and push them to update this PR?

Done 👍

**Comment by crishoj** [comment]
Thanks for the refinements and getting the testcase working!

**Comment by jisotalo** [comment]
Yeah I think I messed up with the remote. I thought I changed it to yours, but it wasn't and I pushed it to my own.

Thanks for the good work! I'll merge this PR later to v2 and release a new beta.

**Pull request merged**
